name: Update Index

on:
  push:
    branches:
      - m  # or whatever branch you want to trigger on

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub

      - name: Update Index
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          python .github/scripts/update_index.py
